### ISSUE TITLE
Why 0.9.0 version?

### ISSUE THREAD

**Issue by ninjazeroone** [pretalx/pretalx-docker#14]
If I'm trying to get the docker installation, it pulls a container from MaxRink/pretalx-devel. It is version 0.9.0, but there's a 1.0.3 version available. Same if I'm trying to choose pretalx/standalone container. Could you please update to the latest version?

**Comment by rixx** [comment]
If you check this out locally, this should work, as the pretalx submodule is pinned to the v1.0.3 version of pretalx. If in doubt, check the state of the submodule.

Other than that, please be aware that this is a community-provided repository, which is not provided nor supported by the pretalx team.

**Comment by saschafoerster** [comment]
Could someone help me, where to change the dockerfile and the docker-compose.yml, so I can build the newest version of pretalx?
