### ISSUE TITLE
Use existing SQL/MariaDB on the main-system (and do not create a separate container)

### ISSUE THREAD

**Issue by saschafoerster** [pretalx/pretalx-docker#16]
I would like to use an existing database on the system next to docker. Most other docker-installations have so environment-variables to describe which external database should be used.

**Comment by rixx** [comment]
Sounds like a good idea! This repository is entirely maintained by the pretalx community, not by the developers, so the only way to make this change is by way of a Pull Request – feel free to submit one!

**Comment by saschafoerster** [comment]
I changed the pretalx.cfg to the following and removed the db-container-settings in docker-compose.yml:

```
[database]
backend=mysql
name=pretalx
user=pretalx
password=REPLACCEPASSWORD
host=/var/run/mysqld/mysqld.sock
```
I am not really shure, if I should change the existing config-files, but I think here someone can find it as a reference.
