### ISSUE TITLE
Mail config not set

### ISSUE THREAD

**Issue by gvarela1981** [pretalx/pretalx-docker#23]
Hi, after setting mail section on conf/pretalx.cfg and runnnig ``` docker-compose up -d ``` and ``` docker exec -ti pretalx pretalx init ``` site loads norally, but mail config is still default when I check ``` domain.com/orga/admin/ ```

Shoul'd I do something to update mail credentials ?

Thanks in advance.

**Comment by rixx** [comment]
I believe there was a bug that prevented the right email configuration from showing in the last pretalx version – it'll be resolved in the next release. It's purely a display issue, though, and the right configuration is applied in practice.

**Comment by rixx** [comment]
Found it, it was https://github.com/pretalx/pretalx/commit/e6fd9c4dfa5b753455ca12d3ee1b6e1d2cfea3dc
