### ISSUE TITLE
update latest tag to latest version

### ISSUE THREAD

**Issue by omercnet** [pretalx/pretalx-docker#26]
switch latest to v2 ?

**Comment by rixx** [comment]
As the Docker support is entirely community maintained, the Docker images are frequently behind the official releases.

I have added another automated build rule to dockerhub that might do the right thing. If it does, it should be triggered by the next release. As I don't have a working Docker setup at the moment, I'm afraid I can't push the image myself.

**Comment by shoetten** [comment]
`latest` is now pointing to [v2.3.2](https://hub.docker.com/layers/pretalx/standalone/v2.3.2/images/sha256-bedafcb43859e7cccd9191aba6e80910327a1856fe6a0e4685d35f7b097d6d16?context=explore), the latest version
