### ISSUE TITLE
Cronjob still needed for docker?

### ISSUE THREAD

**Issue by kuhball** [pretalx/pretalx-docker#27]
Hi, 
thanks for providing this software :+1: While having a look at the documentation, the docker-compose and ansible playbook I noticed a cronjob within the ansible tasks. Is this still needed with having a task worker within the `supervisord.conf` ? If it's still needed it would be helpful to add this to the production tasks within the readme.

Thanks!

**Comment by rixx** [comment]
The cronjob is needed regardless of the worker process, yes. Feel free to add them to this repository – pretalx-docker is community maintained and not officially supported, so it can lag behind in things like this.
