### ISSUE TITLE
Rename the current default branch "master" to "main"

### ISSUE THREAD

**Issue by linux-lukas** [pretalx/pretalx-docker#30]
see: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

**Comment by Lukas2112** [comment]
I had the access to do this, but I did not want to take this step without consulting you first, @rixx

**Comment by rixx** [comment]
You have write access to the repo for a reason – I trust you to use it well ;)

**Comment by Lukas2112** [comment]
Okay, thanks.
