### ISSUE TITLE
Support for Apple Silicon M1

### ISSUE THREAD

**Issue by biancarosa** [pretalx/pretalx-docker#34]
`ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries` when running docker-compose on Apple Silicon M1.

It would be nice to have out of the box support for Apple Silicon M1. Low priority, probably, though :)

**Comment by rixx** [comment]
This repository is entirely community maintained, with no official support – I'd be happy to merge a PR with the required changes, though!

**Comment by biancarosa** [comment]
Just wanted to track! If more people ask for it, I might try to carve time and put a PR for it.
Thank you for answering <3

**Comment by MikkCZ** [comment]
This https://github.com/docker/setup-buildx-action is probably what you need to compile the image for a different platform than the GitHub Actions runner runs on.
