### ISSUE TITLE
v.2024.3.1 did not appear on Docker Hub yet

### ISSUE THREAD

**Issue by saschafoerster** [pretalx/pretalx-docker#70]
v2024.3.1 wasn't pushed to docker hub yet. 
Is this something happening automatically? Or does it need to be pushed manually? 
https://github.com/pretalx/pretalx-docker/actions

**Comment by rixx** [comment]
Given the overall state of the repository, and the fact that pretalx now hard-requires Postgres, I was under the impression that using it in production was hard to impossible (with at least the compose setup using MySQL), and so didn’t prioritise starting the build.

I think I’m giving this repository till the end of the year, and if it’s then still in an ~unusable state, I’ll archive it until somebody steps up to maintain it, tbh. The whole “community-maintained” thing has not been working out well at all. I'll push the tag for v2024.3.1, though.

**Comment by saschafoerster** [comment]
@rixx I would give it a try to maintain it. Do I need special rights to be able to push the container build? It would be my first repository to maintain, but as I am a user, I would enjoy sharing my efforts. Of course, other are welcome to join and help.

**Comment by rixx** [comment]
@saschafoerster cool! I just sent you an invite to be a maintainer for this repo. You should probably take a look at #64 before making big changes, but as long as that PR is not merged, things like removing MySQL etc can’t hurt imo – but I’m leaving it in all the maintainers’ capable hands to decide how to run this repo :)

Re: container build: The build is currently automatically started when you make a new commit with the latest pretalx release referenced, and then tag the commit in the format `v…`. The tag being pushed triggers the Docker build.

(I do try to remember to do this on release, but especially with bugfix releases, I sometimes forget.)
