### ISSUE TITLE
Check new Dockerfile

### ISSUE THREAD

**Issue by rixx** [pretalx/pretalx-docker#8]
@morisson As this repository has been mostly created and done by you – would you mind having a look at the changes I made? I removed the patch file and added a real Dockerfile instead.

(This will help us to remove the Dockerfile from the main repository entirely, and eventually point Dockerhub at this repository, once it's confirmed as working).

Feel free to make any changes you need.

**Comment by morisson** [comment]
@rixx I'll look into it!

**Comment by MaxRink** [comment]
@morisson i've proposed some changes 
https://github.com/pretalx/pretalx-docker/pull/9
It basically moves to a pretix-like standalone container with no need for a fully fledged external Webserver.
